name: Go CI

on:
  push:
    branches:
      - main
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - main

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/cicd/.github/workflows/workflow.yml@v1

    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      disable-version-bumping: false
